site_name: phones
theme:
  name: material
  icon:
    logo: material/alphabet-tengwar
  palette:
    primary: black
  favicon: images/favicon.png
nav:
- Home: index.md
- Usage:
    Loading a Phone Collection: examples/basic_usage.ipynb
    Mapping between Languages: examples/mapping_phones.ipynb
    Converting between Alphabets: examples/convert_alphabets.ipynb
    Working with Distances: examples/phone_distances.ipynb
- API Reference: reference.md

extra_css:
  - stylesheets/hide_prompts.css

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        selection:
          filters:
            - "!^_"  # exlude all members starting with _
            - "^__init__$"  # but always include __init__ modules and methods
            - "^__getitem__$"
        setup_commands:
            - import sys
            - sys.path.append("src")
            - from unittest.mock import MagicMock as mock
            - sys.modules["distance"] = mock()
            - sys.modules["distance.euclidean"] = mock()
    watch:
    - src/phones
- mkdocs-jupyter

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - tables
  - toc:
      permalink: "#"
  - markdown_include.include:
      base_path: docs