name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "*.md"
      - docs/**
      - .github/workflows/doc.yml
      - "src/phones/**"

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: "x64"
      - name: Install Dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -
          pdm install -G docs
      - name: Build Documentation
        run: cd docs && pdm run mkdocs build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site